/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountPassword: typeof import('./../../../src/components/LoginDialog/components/FormLogin/AccountPassword.vue')['default']
    IconSelect: typeof import('./../../../src/components/IconSelect/index.vue')['default']
    LoginDialog: typeof import('./../../../src/components/LoginDialog/index.vue')['default']
    ModelSelect: typeof import('./../../../src/components/ModelSelect/index.vue')['default']
    Popover: typeof import('./../../../src/components/Popover/index.vue')['default']
    QrCodeLogin: typeof import('./../../../src/components/LoginDialog/components/QrCodeLogin/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../../../src/components/SvgIcon/index.vue')['default']
    VerificationCode: typeof import('./../../../src/components/LoginDialog/components/FormLogin/VerificationCode.vue')['default']
    WelecomeText: typeof import('./../../../src/components/WelecomeText/index.vue')['default']
  }
}
